# Site settings
title: UX Compass
email: chris@northswiss.com
description: > # this means to ignore newlines until "baseurl:"
  UX Copmpass is a work in progress...

host: "startersite.dev"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:3000" # the base hostname & protocol for your site
permalink: pretty
exclude: [node_modules, gulpfile.js]

port: 8080

# Build settings
markdown: kramdown
jquery_version: 1.11.3
modernizr:  true
post_dirs: true

# Site defaults
defaults:
  -
    scope:
      path: "/blog/"
      type: "posts"
    values:
      layout: "post"
      author: "Chris Roy"
  -
    scope:
      path: ""
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page" # overrides previous default layout

# Compress HTML settings via http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  ignore:
    envs: [local]

sass:
    sass_dir: _sass
    style: compressed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - readme.md

social:
  linkedin: http://linkedin.com
  twitter: http://twitter.com
  facebook: http://facebook.com
  github: https://github.com/uxcompass/uxcompass.github.io
