# Site settings
title: YOUR SITE
email: YOUR-EMAIL@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

host: "startersite.dev"
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: pretty
exclude: [node_modules, gulpfile.js]

port: 8080

# Build settings
markdown: kramdown
jquery_version: 1.11.3
modernizr:  true

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "YOUR NAME"
  -
    scope:
      path: ""
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page" # overrides previous default layout

# Compress HTML settings via http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  ignore:
    envs: [local]

sass:
    sass_dir: _sass
    style: compressed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - readme.md

social:
  linkedin: http://linkedin.com
  twitter: http://twitter.com
  facebook: http://facebook.com
